export const STUDENT_TYPE = "STUDENT_TYPE";
export const PERSONAL_WEB_TYPE = "PERSONAL_WEB_TYPE";
export const COMPANY_WEB_TYPE = "COMPANY_WEB_TYPE";
export const SHOP_SITE_TYPE = "SHOP_SITE_TYPE";
export const SERVICE_SITE_TYPE = "SERVICE_SITE_TYPE";
export const APPLICATION_TYPE = "APPLICATION_TYPE";
export const OTHER_TYPE = "OTHER_TYPE";